# Generated by Django 3.2.5 on 2021-12-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='message',
        ),
    ]
