# Generated by Django 3.2.5 on 2021-08-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='img_url',
            new_name='image',
        ),
    ]
