# Generated by Django 3.2.5 on 2021-08-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_img_url_listing_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='textfield',
        ),
    ]
