# Generated by Django 3.2.5 on 2021-08-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_rename_content_comment_textfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='winner',
            new_name='final_bider',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='begining_bid',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='winner',
            new_name='final_bider',
        ),
    ]
