# Generated by Django 3.2.5 on 2021-12-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.CharField(default=None, max_length=240),
        ),
    ]
