# Generated by Django 3.2.5 on 2021-08-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_watchlist_watching'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watching',
            field=models.BooleanField(default=False),
        ),
    ]
